run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
